"use client";
import {useMemo,useState} from "react";
import {BookOpen,Search,Heart,ArrowUpRight,Library,CheckCircle2,Clock3,Download,LoaderCircle,Grid2X2,List} from "lucide-react";
import type {BookEntry} from "@/lib/catalog";
import type {EmployeeLibrary} from "@/hooks/use-employee-library";

type Props={library:EmployeeLibrary;books:BookEntry[];onOpen:(book:BookEntry)=>void;onManage:()=>void;onImport:()=>void};
export default function LibraryShelf({library,books,onOpen,onManage,onImport}:Props){
 const [query,setQuery]=useState(""),[category,setCategory]=useState("all"),[tab,setTab]=useState("all"),[sort,setSort]=useState("recent"),[list,setList]=useState(false),[download,setDownload]=useState(""),[notice,setNotice]=useState("");
 const [visible,setVisible]=useState(24);
 const categories=useMemo(()=>[...new Set(books.map(b=>b.category||"General"))].sort(),[books]);
 const filtered=useMemo(()=>books.filter(book=>{
  const record=library.records[book.id],needle=query.toLocaleLowerCase().trim();
  return (!needle||[book.title,book.author,book.description,book.category].some(v=>v?.toLocaleLowerCase().includes(needle)))&&(category==="all"||(book.category||"General")===category)&&(tab==="all"||tab==="saved"&&record?.favorite||tab==="reading"&&record?.started&&!record.completed||tab==="completed"&&record?.completed);
 }).sort((a,b)=>sort==="title"?a.title.localeCompare(b.title):sort==="progress"?(library.records[b.id]?.percent||0)-(library.records[a.id]?.percent||0):(b.addedAt||"").localeCompare(a.addedAt||"")),[books,library.records,query,category,tab,sort]);
 const continuing=books.filter(b=>library.records[b.id]?.started&&!library.records[b.id].completed).sort((a,b)=>(library.records[b.id].lastReadAt||"").localeCompare(library.records[a.id].lastReadAt||""));
 const completed=books.filter(b=>library.records[b.id]?.completed).length;
 async function saveOffline(book:BookEntry){setDownload(book.id);setNotice("");try{await library.download(book);setNotice(`“${book.title}” is saved on this device for offline reading while signed in.`);}catch(error){setNotice(error instanceof Error?error.message:"Could not save this book offline.");}finally{setDownload("");}}
 return <main className="employee-library"><div className="shelf-heading"><div><p className="eyebrow">THE TOYOTA EMPLOYEE LIBRARY</p><h1>{library.user?`Hello, ${library.user.name.split(" ")[0]}.`:"A good place to turn a page."}</h1><p>Make room for a new idea. Your next read is waiting.</p></div><div className="shelf-summary"><div><strong>{books.length}</strong><span>Books to explore</span></div>{library.user&&<><div><strong>{continuing.length}</strong><span>In progress</span></div><div><strong>{completed}</strong><span>Completed</span></div></>}</div></div>
  {!!Object.keys(library.conflicts).length&&<div className="conflict-panel" role="alert"><strong>There’s a newer reading record on another device.</strong><p>Choose a copy for each book. Your notes and bookmarks are included.</p>{Object.entries(library.conflicts).map(([id,cloud])=><div key={id}><span>{books.find(b=>b.id===id)?.title||"Archived book"}<small>Server: {Math.round(cloud.percent)}% · This device: {Math.round(library.records[id]?.percent||0)}%</small></span><button className="toolbar-button" onClick={()=>library.resolveConflict(id,false)}>Use server copy</button><button className="toolbar-button" onClick={()=>library.resolveConflict(id,true)}>Keep this device’s copy</button></div>)}</div>}
  {continuing.length>0&&tab==="all"&&!query&&category==="all"&&<section className="continue-strip"><div className="continue-copy"><span className="shelf-kicker"><Clock3 size={16}/> PICK UP WHERE YOU LEFT OFF</span><h2>{continuing[0].title}</h2><p>{continuing[0].author}</p><div className="book-progress"><span style={{width:library.records[continuing[0].id].percent+"%"}}/></div><small>{Math.round(library.records[continuing[0].id].percent)}% read{continuing[0].format==="pdf"?` · Page ${library.records[continuing[0].id].page}`:""}</small></div><button className="primary-button" onClick={()=>onOpen(continuing[0])}>Continue reading<ArrowUpRight size={18}/></button></section>}
  <section aria-label="Book catalog"><div className="catalog-heading"><h2>Explore the collection<span>{filtered.length}</span></h2>{library.user?.role==="admin"&&<button className="toolbar-button" onClick={onManage}><Library size={18}/> Manage library</button>}</div>
   <div className="catalog-filters"><label className="catalog-search"><Search size={19}/><input aria-label="Search books by title, author or topic" placeholder="Search titles, authors, topics…" value={query} onChange={e=>{setQuery(e.target.value);setVisible(24);}}/></label><select aria-label="Filter by collection" value={category} onChange={e=>{setCategory(e.target.value);setVisible(24);}}><option value="all">All collections</option>{categories.map(c=><option key={c}>{c}</option>)}</select><select aria-label="Sort books" value={sort} onChange={e=>{setSort(e.target.value);setVisible(24);}}><option value="recent">Recently added</option><option value="title">Title A–Z</option><option value="progress">Reading progress</option></select><button className="icon-button" aria-label={list?"Switch to grid view":"Switch to list view"} onClick={()=>setList(!list)}>{list?<Grid2X2 size={19}/>:<List size={19}/>}</button></div>
   {library.user&&<div className="shelf-tabs" role="group" aria-label="Your reading shelves">{[["all","All books"],["reading","In progress"],["saved","Favorites"],["completed","Completed"]].map(([value,label])=><button key={value} aria-pressed={tab===value} onClick={()=>{setTab(value);setVisible(24);}}>{label}</button>)}</div>}
   {notice&&<p className="shelf-notice" role="status">{notice}</p>}
   <div className={"catalog-grid "+(list?"catalog-list":"")}>{filtered.slice(0,visible).map((entry,index)=>{const record=library.records[entry.id];return <article key={entry.id} className="catalog-book"><button className={"catalog-cover cover-color-"+index%4} aria-label={"Open "+entry.title} onClick={()=>onOpen(entry)}>{entry.cover?<img src={entry.cover} alt=""/>:<><span>{entry.category||"TOYOTA LIBRARY"}</span><strong>{entry.title}</strong><small>{entry.author}</small><BookOpen size={24}/></>}<span className="format-badge">{entry.format.toUpperCase()}</span></button><div className="catalog-book-body"><div className="book-card-top"><span>{entry.category||"General"}</span>{library.user&&!entry.personal&&<button className={"favorite-button "+(record?.favorite?"is-favorite":"")} aria-label={(record?.favorite?"Remove from":"Add to")+" favorites: "+entry.title} aria-pressed={!!record?.favorite} onClick={()=>library.update(entry.id,{favorite:!record?.favorite})}><Heart size={18} fill={record?.favorite?"currentColor":"none"}/></button>}</div><h3>{entry.title}</h3><p>{entry.author}</p>{entry.description&&<p className="catalog-description">{entry.description}</p>}<div className="card-reading-status">{record?.completed?<span><CheckCircle2 size={15}/> Completed</span>:record?.started?<><div className="book-progress"><span style={{width:record.percent+"%"}}/></div><small>{Math.round(record.percent)}% read</small></>:<span>{entry.pages?`${entry.pages} pages · `:""}{entry.language.toUpperCase()}</span>}</div><div className="catalog-card-actions"><button className="card-open" onClick={()=>onOpen(entry)}>{record?.started&&!record.completed?"Continue reading":"Open book"}<ArrowUpRight size={17}/></button>{library.user&&!entry.personal&&<button className="icon-button" disabled={!!download} aria-label={"Save offline: "+entry.title} title="Save a copy on this device" onClick={()=>void saveOffline(entry)}>{download===entry.id?<LoaderCircle size={17} className="reader-spinner"/>:<Download size={17}/>}</button>}</div></div></article>;})}</div>
   {filtered.length>visible&&<div className="catalog-more"><button className="toolbar-button" onClick={()=>setVisible(count=>count+24)}>Show more books ({filtered.length-visible} remaining)</button></div>}
   {!filtered.length&&<div className="library-empty"><BookOpen size={36}/><h3>{tab==="saved"?"Your favorites will appear here.":tab==="reading"?"Your next chapter is waiting.":tab==="completed"?"Every finished book is a step forward.":"No books match your search."}</h3><p>{query||category!=="all"?"Try another title or collection.":"Explore the collection and open a book to get started."}</p><button className="toolbar-button" onClick={()=>{setQuery("");setCategory("all");setTab("all");setVisible(24);}}>Explore all books</button></div>}
  </section><footer className="shelf-footer"><span><BookOpen size={17}/> {library.user?"Your progress stays with your employee ID.":"Guest reading — sign in to keep your progress."}</span><button className="toolbar-button" onClick={onImport}>Open a personal file</button></footer>
 </main>;
}
