"use client";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {Upload,Users,BookOpen,Check,LoaderCircle,FileText,Plus,RefreshCw} from "lucide-react";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {api,type Employee} from "@/lib/employee-library";
import {parseEmployeeCsv} from "@/lib/employee-csv.mjs";
import type {BookEntry} from "@/lib/catalog";
import type {EmployeeLibrary} from "@/hooks/use-employee-library";
type AccountInput={employeeId:string;name:string;pin:string;role:string};
type UploadItem={file:File;status:string;state:"waiting"|"uploading"|"done"|"error"};

export default function LibraryManager({library,onClose,onBusyChange}:{library:EmployeeLibrary;onClose:()=>void;onBusyChange:(busy:boolean)=>void}){
 const [tab,setTab]=useState("books"),[books,setBooks]=useState<BookEntry[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[usage,setUsage]=useState<Record<string,number>>({});
 const [loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const [selected,setSelected]=useState<string[]>([]),[bulkCategory,setBulkCategory]=useState(""),[bookQuery,setBookQuery]=useState(""),[bookStatus,setBookStatus]=useState("all");
 const filteredBooks=useMemo(()=>books.filter(book=>(bookStatus==="all"||(bookStatus==="active"?book.active:!book.active))&&[book.title,book.author,book.category].some(text=>text?.toLowerCase().includes(bookQuery.toLowerCase()))),[books,bookQuery,bookStatus]);
 const [items,setItems]=useState<UploadItem[]>([]),[uploading,setUploading]=useState(false),[category,setCategory]=useState("General"),[author,setAuthor]=useState("Toyota library"),[language,setLanguage]=useState("en");
 const [edit,setEdit]=useState<BookEntry|null>(null),[account,setAccount]=useState<Employee|null>(null),[replacement,setReplacement]=useState(""),[saving,setSaving]=useState(false);
 const [employeeId,setEmployeeId]=useState(""),[name,setName]=useState(""),[pin,setPin]=useState(""),[role,setRole]=useState("employee"),[batch,setBatch]=useState<AccountInput[]>([]),[results,setResults]=useState<Array<{employeeId:string;ok?:boolean;error?:string}>>([]);
 const controller=useRef<AbortController|null>(null),closed=useRef(false),importInput=useRef<HTMLInputElement>(null);
 useEffect(()=>{onBusyChange(uploading||saving);return()=>onBusyChange(false);},[uploading,saving,onBusyChange]);
 const refreshLibrary=library.refresh;
 const refresh=useCallback(async(signal?:AbortSignal)=>{setLoading(true);setError("");try{const [catalog,directory]=await Promise.all([api<{books:BookEntry[];usage:Record<string,number>}>("/api/admin/books",{signal}),api<{employees:Employee[]}>("/api/admin/employees",{signal})]);if(closed.current||signal?.aborted)return;setBooks(catalog.books);setUsage(catalog.usage);setEmployees(directory.employees);}catch(error){if(!signal?.aborted&&!closed.current)setError(error instanceof Error?error.message:"Could not load the library.");}finally{if(!signal?.aborted&&!closed.current)setLoading(false);}},[]);
 useEffect(()=>{closed.current=false;const c=new AbortController();void refresh(c.signal);return()=>{closed.current=true;c.abort();controller.current?.abort();};},[refresh]);
 function chooseFiles(files:File[]){setError("");setNotice("");if(files.length>100){setError("Choose up to 100 books per batch.");return;}setItems(files.map(file=>({file,status:"Ready to upload",state:"waiting"})));}
 async function upload(){
  setUploading(true);setError("");controller.current=new AbortController();const signal=controller.current.signal;
  for(let index=0;index<items.length;index++){
   if(signal.aborted)break;
   if(items[index].state==="done")continue;
   setItems(list=>list.map((item,i)=>i===index?{...item,state:"uploading",status:"Uploading…"}:item));
   const file=items[index].file;
   try{
    if(!/\.(pdf|epub)$/i.test(file.name))throw new Error("Choose a PDF or EPUB file.");
    if(file.size>50*1024*1024)throw new Error("File exceeds 50 MB.");
    const params=new URLSearchParams({filename:file.name,category,author,language});
    const result=await api<{duplicate:boolean;book:BookEntry}>("/api/admin/books?"+params,{method:"POST",body:file,signal,headers:{"Content-Type":"application/octet-stream"}});
    if(closed.current)break;setItems(list=>list.map((item,i)=>i===index?{...item,state:"done",status:result.duplicate?result.book.active?"Already in library — skipped":"Already archived — restore it in catalog":"Added to library"}:item));
   }catch(error){if(closed.current)break;setItems(list=>list.map((item,i)=>i===index?{...item,state:"error",status:signal.aborted?"Upload interrupted. Retry safely; duplicates are skipped.":error instanceof Error?error.message:"Upload failed."}:item));}
  }
  if(!closed.current){setUploading(false);await refresh();try{await refreshLibrary();}catch{setError("Uploads were saved, but the catalog could not refresh. Try Refresh.");}}
 }
 async function saveBook(event:React.FormEvent){event.preventDefault();if(!edit)return;setSaving(true);setError("");try{await api("/api/admin/books/"+edit.id,{method:"PUT",body:JSON.stringify(edit)});setEdit(null);await refresh();await refreshLibrary();setNotice("Catalog updated. Archived books keep employee reading records.");}catch(error){setError(error instanceof Error?error.message:"Could not update the book.");}finally{setSaving(false);}}
 async function bulkChange(change:Partial<BookEntry>){setSaving(true);setError("");let success=0;const failures:string[]=[];for(const id of selected){const book=books.find(book=>book.id===id);if(!book)continue;try{await api("/api/admin/books/"+id,{method:"PUT",body:JSON.stringify({...book,...change})});success++;}catch{failures.push(book.title);}}setSelected([]);setNotice(`${success} books updated. Employee reading records are preserved.`);if(failures.length)setError(`Could not update: ${failures.join(", ")}. Retry those books.`);await refresh();try{await refreshLibrary();}catch{}setSaving(false);}
 async function addEmployees(entries:AccountInput[]){setSaving(true);setError("");setResults([]);try{const response=await api<{results:typeof results}>("/api/admin/employees",{method:"POST",body:JSON.stringify({employees:entries})});setResults(response.results);setPin("");setBatch([]);if(importInput.current)importInput.current.value="";await refresh();}catch(error){setError(error instanceof Error?error.message:"Could not create accounts.");}finally{setSaving(false);}}
 async function importEmployees(file?:File){setError("");if(!file)return;try{if(file.size>200000)throw new Error("Choose a CSV smaller than 200 KB.");setBatch(parseEmployeeCsv(await file.text()));}catch(error){setError(error instanceof Error?error.message:"Could not read this CSV.");}}
 async function saveAccount(event:React.FormEvent){event.preventDefault();if(!account)return;setSaving(true);setError("");try{await api("/api/admin/employees/"+account.id,{method:"PUT",body:JSON.stringify({active:account.active,...(replacement?{pin:replacement}:{})})});setAccount(null);setReplacement("");setNotice("Employee access updated. Existing sessions were revoked if the PIN changed or access was paused.");await refresh();}catch(error){setError(error instanceof Error?error.message:"Could not update access.");}finally{setSaving(false);}}
 return <Dialog open onOpenChange={open=>{if(!open&&!uploading&&!saving)onClose();}}><DialogContent className="library-manager" onEscapeKeyDown={e=>{if(uploading||saving)e.preventDefault();}} onPointerDownOutside={e=>{if(uploading||saving)e.preventDefault();}}><DialogTitle>Library administration</DialogTitle><DialogDescription>Build the collection and manage employee access.</DialogDescription>
  <div className="manager-tabs"><button aria-pressed={tab==="books"} onClick={()=>setTab("books")}><BookOpen size={18}/> Book catalog</button><button aria-pressed={tab==="employees"} onClick={()=>setTab("employees")}><Users size={18}/> Employees</button><button className="toolbar-button" disabled={loading||uploading||saving} onClick={()=>void refresh()}><RefreshCw size={16}/> Refresh</button></div>
  {error&&<p className="library-alert" role="alert">{error}</p>}{notice&&<p className="shelf-notice" role="status">{notice}</p>}
  {loading?<div className="manager-loading" role="status"><LoaderCircle className="reader-spinner"/> Loading library records…</div>:tab==="books"?<>
   <section className="bulk-panel"><div><span className="shelf-kicker">GROW THE COLLECTION</span><h3>Add books in a batch.</h3><p>Select or drop up to 100 PDF/EPUB files. Each book can be up to 50 MB. Matching files are skipped automatically.</p></div><div className="bulk-defaults"><label>Collection<input value={category} onChange={e=>setCategory(e.target.value)} maxLength={80} disabled={uploading}/></label><label>Author / publisher<input value={author} onChange={e=>setAuthor(e.target.value)} maxLength={200} disabled={uploading}/></label><label>Book language<select value={language} onChange={e=>setLanguage(e.target.value)} disabled={uploading}><option value="en">English</option><option value="ja">Japanese</option><option value="kn">Kannada</option><option value="hi">Hindi</option></select></label></div>
    <label className="bulk-drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!uploading)chooseFiles(Array.from(e.dataTransfer.files));}}><Upload size={26}/><strong>Drop books here or choose files</strong><span>PDF & EPUB · multiple files supported</span><input type="file" multiple accept=".pdf,.epub" aria-label="Choose books for bulk upload" disabled={uploading} onChange={e=>chooseFiles(Array.from(e.target.files||[]))}/></label>
    {!!items.length&&<><div className="upload-list" aria-label="Batch upload results" aria-live="polite">{items.map((item,index)=><div key={index}><FileText size={17}/><span>{item.file.name}<small>{(item.file.size/1024/1024).toFixed(1)} MB</small></span><span className={"upload-status "+item.state}>{item.state==="uploading"?<LoaderCircle size={15} className="reader-spinner"/>:item.state==="done"?<Check size={15}/>:null}{item.status}</span></div>)}</div><div className="bulk-actions"><span>{items.filter(i=>i.state==="done").length} / {items.length} processed</span>{uploading?<button className="toolbar-button" onClick={()=>controller.current?.abort()}>Cancel remaining uploads</button>:<button className="primary-button" disabled={!items.some(i=>i.state!=="done")||!category.trim()||!author.trim()} onClick={()=>void upload()}><Upload size={17}/> Upload {items.filter(i=>i.state!=="done").length} books</button>}</div></>}
   </section><div className="manager-section-title"><h3>Catalog · {books.length} books</h3><p>Edit details, assign collections, or archive a book.</p></div><div className="manager-catalog-tools"><input aria-label="Search administration catalog" placeholder="Search the catalog…" value={bookQuery} onChange={e=>setBookQuery(e.target.value)}/><select aria-label="Filter book availability" value={bookStatus} onChange={e=>setBookStatus(e.target.value)}><option value="all">All statuses</option><option value="active">Available books</option><option value="archived">Archived books</option></select></div>{!!selected.length&&<div className="bulk-book-controls"><strong>{selected.length} selected</strong><input aria-label="New collection for selected books" placeholder="New collection" value={bulkCategory} onChange={e=>setBulkCategory(e.target.value)} maxLength={80}/><button className="toolbar-button" disabled={saving||uploading||!bulkCategory.trim()} onClick={()=>void bulkChange({category:bulkCategory})}>Move to collection</button><button className="toolbar-button" disabled={saving||uploading} onClick={()=>void bulkChange({active:false})}>Archive selected</button><button className="toolbar-button" disabled={saving||uploading} onClick={()=>void bulkChange({active:true})}>Restore selected</button><button className="toolbar-button" disabled={saving} onClick={()=>setSelected([])}>Clear selection</button></div>}<div className="manager-table-wrap"><table><thead><tr><th><label className="table-selection"><input type="checkbox" aria-label="Select up to 100 visible books" checked={filteredBooks.length>0&&filteredBooks.slice(0,100).every(b=>selected.includes(b.id))} disabled={saving||uploading} onChange={e=>setSelected(e.target.checked?filteredBooks.slice(0,100).map(b=>b.id):[])}/></label></th><th>Book</th><th>Collection</th><th>Readers</th><th>Status</th><th>Action</th></tr></thead><tbody>{filteredBooks.map(book=><tr key={book.id}><td><label className="table-selection"><input type="checkbox" aria-label={"Select "+book.title} checked={selected.includes(book.id)} disabled={saving||uploading||selected.length>=100&&!selected.includes(book.id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,book.id]:ids.filter(id=>id!==book.id))}/></label></td><td><strong>{book.title}</strong><small>{book.author} · {book.format.toUpperCase()}</small></td><td>{book.category}</td><td>{usage[book.id]||0}</td><td><span className={book.active?"status-active":"status-archived"}>{book.active?"Available":"Archived"}</span></td><td><button className="toolbar-button" disabled={uploading} onClick={()=>{setError("");setEdit({...book});}}>Edit details</button></td></tr>)}</tbody></table>{!books.length&&<p className="library-empty">Your collection is empty. Add a batch of books above.</p>}</div>
  </>:<>
   <section className="employee-create"><div><h3>Add employee access</h3><p>Provide the employee’s ID and an initial PIN or passphrase. They can change their PIN after signing in.</p></div><form onSubmit={e=>{e.preventDefault();void addEmployees([{employeeId,name,pin,role}]);}}><label>Employee ID<input value={employeeId} onChange={e=>setEmployeeId(e.target.value)} required maxLength={40}/></label><label>Full name<input value={name} onChange={e=>setName(e.target.value)} required maxLength={100}/></label><label>Initial PIN<input type="password" autoComplete="new-password" value={pin} onChange={e=>setPin(e.target.value)} required minLength={6} maxLength={128}/></label><label>Access role<select value={role} onChange={e=>setRole(e.target.value)}><option value="employee">Employee</option><option value="admin">Library administrator</option></select></label><button className="primary-button" disabled={saving}><Plus size={17}/> Add employee</button></form></section>
   <section className="employee-import"><div><h3>Import an employee list</h3><p>CSV columns: <code>employeeId,name,pin</code> and optional <code>role</code>. Import up to 200 accounts. Existing IDs keep their credentials.</p></div><label className="csv-picker">Choose employee CSV<input ref={importInput} type="file" accept=".csv,text/csv" disabled={saving} onChange={e=>void importEmployees(e.target.files?.[0])}/></label>{!!batch.length&&<div className="batch-preview"><p>{batch.length} employees ready: {batch.slice(0,5).map(e=>`${e.employeeId} (${e.name})`).join(", ")}{batch.length>5?"…":""}</p><button className="primary-button" disabled={saving} onClick={()=>void addEmployees(batch)}>Add {batch.length} employees</button><button className="toolbar-button" onClick={()=>setBatch([])} disabled={saving}>Clear list</button></div>}{!!results.length&&<div className="employee-import-results" role="status">{results.map((r,i)=><p key={i} className={r.ok?"import-success":"import-error"}>{r.employeeId}: {r.ok?"Account created":r.error}</p>)}</div>}</section>
   <div className="manager-section-title"><h3>Employee directory · {employees.length}</h3><p>Pause access or reset a PIN. Reading records are preserved.</p></div><div className="manager-table-wrap"><table><thead><tr><th>Employee</th><th>ID</th><th>Role</th><th>Status</th><th>Action</th></tr></thead><tbody>{employees.map(employee=><tr key={employee.id}><td><strong>{employee.name}</strong></td><td>{employee.employeeId}</td><td>{employee.role==="admin"?"Administrator":"Employee"}</td><td><span className={employee.active?"status-active":"status-archived"}>{employee.active?"Active":"Paused"}</span></td><td>{employee.id===library.user?.id?<span className="directory-self">Your account</span>:<button className="toolbar-button" disabled={saving} onClick={()=>{setError("");setReplacement("");setAccount({...employee});}}>Manage access</button>}</td></tr>)}</tbody></table></div>
  </>}
  <Dialog open={!!edit} onOpenChange={open=>{if(!open&&!saving)setEdit(null);}}><DialogContent className="library-edit"><DialogTitle>Edit book details</DialogTitle><DialogDescription>Organize how this book appears in the employee library.</DialogDescription>{edit&&<form onSubmit={saveBook}><label>Title<input value={edit.title} onChange={e=>setEdit({...edit,title:e.target.value})} required maxLength={200}/></label><label>Author<input value={edit.author} onChange={e=>setEdit({...edit,author:e.target.value})} required maxLength={200}/></label><label>Collection<input value={edit.category||""} onChange={e=>setEdit({...edit,category:e.target.value})} required maxLength={80}/></label><label>Description<textarea value={edit.description||""} onChange={e=>setEdit({...edit,description:e.target.value})} maxLength={3000}/></label><label>Language code<input value={edit.language} onChange={e=>setEdit({...edit,language:e.target.value})} required maxLength={30}/></label><label className="checkbox-label"><input type="checkbox" checked={edit.active!==false} onChange={e=>setEdit({...edit,active:e.target.checked})}/> Available to employees</label><p>Uncheck to archive this book. Its file and all saved reading records remain in the library.</p>{error&&<p className="library-alert" role="alert">{error}</p>}<button className="primary-button" disabled={saving}>{saving?"Saving…":"Save book details"}</button></form>}</DialogContent></Dialog>
  <Dialog open={!!account} onOpenChange={open=>{if(!open&&!saving)setAccount(null);}}><DialogContent className="library-edit"><DialogTitle>Manage employee access</DialogTitle><DialogDescription>{account?.name} · {account?.employeeId}</DialogDescription>{account&&<form onSubmit={saveAccount}><label>New PIN or passphrase<input type="password" autoComplete="new-password" value={replacement} onChange={e=>setReplacement(e.target.value)} minLength={6} maxLength={128}/></label><p>Leave empty to keep the current PIN. A reset ends existing sessions.</p><label className="checkbox-label"><input type="checkbox" checked={account.active} onChange={e=>setAccount({...account,active:e.target.checked})}/> Employee access is active</label>{error&&<p className="library-alert" role="alert">{error}</p>}<button className="primary-button" disabled={saving}>{saving?"Saving…":"Save access"}</button></form>}</DialogContent></Dialog>
 </DialogContent></Dialog>;
}
